import{classifyOrbit}from"../systems/stellar/habitability.js";import{createBigBangController}from"../systems/stellar/big-bang.js";import{findOrbitConflict}from"../systems/stellar/orbital-collisions.js";
const isEntity=(engine,id,type)=>Boolean(id&&engine.world.get(id)?.type===type);
const template=(engine,id,category)=>engine.templates.get(id)?.category===category;
const entityFromTemplate=(engine,type,templateId,input,extra={})=>engine.create(type,{...engine.templates.get(templateId).baseProperties,...input,templateId,...extra});

export const CosmicPowersModule={
 id:"cosmic-powers",version:"1.3.0",
 install(engine){
  engine.bigBang=createBigBangController(engine);
  engine.powers.register({id:"BIG_BANG",name:"Big Bang regional",version:"3.0.0",requirements:["systemId"],validate:({engine,input})=>{const region=engine.world.get(input.systemId);if(!region||region.type!=="cosmic.star-system"||region.parentSystemId)return "BIG_BANG requires a top-level empty region";if(engine.bigBang.status().active)return "BIG_BANG is already active";const occupied=[...engine.world.byType("cosmic.star"),...engine.world.byType("cosmic.terrestrial-planet"),...engine.world.byType("cosmic.black-hole")].some(body=>body.systemId===region.id);if(occupied)return "BIG_BANG requires an empty region";return true},execute:({engine,input})=>engine.bigBang.start({systemId:input.systemId,seed:input.seed??Date.now(),bounds:input.bounds})});
  engine.powers.register({id:"CREATE_SYSTEM",name:"Criar sistema estelar",version:"1.0.0",requirements:["universeId"],validate:({engine,input})=>isEntity(engine,input.universeId,"cosmic.empty-space")||"CREATE_SYSTEM requires a valid universeId",execute:({engine,input})=>{const system=engine.create("cosmic.star-system",input);engine.bus.emit("system:created",system);return system}});
  engine.powers.register({id:"CREATE_STAR",name:"Criar estrela",version:"1.0.0",requirements:["systemId","templateId"],validate:({engine,input})=>isEntity(engine,input.systemId,"cosmic.star-system")&&template(engine,input.templateId,"star")||"CREATE_STAR requires a valid systemId and star template",execute:({engine,input})=>{const star=entityFromTemplate(engine,"cosmic.star",input.templateId,input,{systemId:input.systemId});engine.bus.emit("star:created",star);return star}});
  engine.powers.register({id:"CREATE_BLACK_HOLE",name:"Criar buraco negro",version:"1.0.0",requirements:["systemId","positionAU"],validate:({engine,input})=>isEntity(engine,input.systemId,"cosmic.star-system")&&Number.isFinite(input.massSolar??10)&&(input.massSolar??10)>0&&Number.isFinite(input.positionAU?.x)&&Number.isFinite(input.positionAU?.y)||"CREATE_BLACK_HOLE requires a system, positive mass, and AU coordinates",execute:({engine,input})=>{const blackHole=engine.create("cosmic.black-hole",{...input,massSolar:input.massSolar??10});engine.bus.emit("black-hole:created",blackHole);return blackHole}});
  engine.powers.register({id:"CREATE_PLANET",name:"Criar planeta",version:"1.1.0",requirements:["systemId","parentStarId","templateId","semiMajorAxisAU","periodDays"],validate:({engine,input})=>{if(!isEntity(engine,input.systemId,"cosmic.star-system"))return "CREATE_PLANET requires a valid systemId";const star=engine.world.get(input.parentStarId);if(!star||star.type!=="cosmic.star"||star.systemId!==input.systemId)return "CREATE_PLANET requires a star in the selected system";if(!template(engine,input.templateId,"planet"))return "CREATE_PLANET requires a planet template";if(!(input.semiMajorAxisAU>0)||!(input.periodDays>0)||input.eccentricity<0||input.eccentricity>=1)return "CREATE_PLANET requires valid orbital parameters";if(findOrbitConflict(engine,input))return "CREATE_PLANET requires an unoccupied orbit";return true},execute:({engine,input})=>{const orbit=engine.create("cosmic.orbit",input);const star=engine.world.get(input.parentStarId);const environment=classifyOrbit(star,orbit.semiMajorAxisAU);const planet=entityFromTemplate(engine,"cosmic.terrestrial-planet",input.templateId,input,{systemId:input.systemId,parentStarId:input.parentStarId,orbitId:orbit.id,environment,orbit:{semiMajorAxisAU:orbit.semiMajorAxisAU,eccentricity:orbit.eccentricity,phaseRadians:orbit.phaseRadians,periodDays:orbit.periodDays,parentStarId:orbit.parentStarId}});engine.bus.emit("planet:created",planet);engine.bus.emit("planet:placed",Object.freeze({planetId:planet.id,orbitId:orbit.id,systemId:input.systemId,parentStarId:input.parentStarId}));return Object.freeze({planet,orbit})}});
  engine.powers.register({id:"DESTROY_PLANET",name:"Destruir planeta",version:"1.0.0",requirements:["planetId"],validate:({engine,input})=>isEntity(engine,input.planetId,"cosmic.terrestrial-planet")||"DESTROY_PLANET requires a valid planetId",execute:({engine,input})=>{const planet=engine.world.get(input.planetId);const orbitId=planet.orbitId;const removedPlanet=engine.remove(planet.id);const removedOrbit=orbitId?engine.remove(orbitId):null;const result=Object.freeze({planet:removedPlanet,orbit:removedOrbit});engine.bus.emit("planet:destroyed",result);return result}});
 }
};
