import{classifyOrbit}from"../systems/stellar/habitability.js";import{createBigBangController}from"../systems/stellar/big-bang.js";import{findOrbitConflict}from"../systems/stellar/orbital-collisions.js";
import{createMechanicContext}from"../core/mechanic-registry.js";
const isEntity=(engine,id,type)=>Boolean(id&&engine.world.get(id)?.type===type);
const template=(engine,id,category)=>engine.templates.get(id)?.category===category;
const entityFromTemplate=(engine,type,templateId,input,extra={})=>engine.create(type,{...engine.templates.get(templateId).baseProperties,...input,templateId,...extra});
const registerSDKPower=(engine,power)=>{const validate=power.validate,execute=power.execute;engine.powers.register({...power,validate:args=>validate({context:args?.context??createMechanicContext(args?.engine),input:args?.input??{}}),execute:args=>execute({context:args?.context??createMechanicContext(args?.engine),input:args?.input??{}})})};

export const CosmicPowersModule={
 id:"cosmic-powers",version:"1.3.0",
 install(engine){
  engine.bigBang=createBigBangController(engine);
  engine.powers.register({id:"BIG_BANG",name:"Big Bang regional",version:"3.0.0",presentation:{label:"Big Bang raro",icon:"✹",description:"Povoar uma região à medida que você explora.",surface:"inventory",interaction:"bigbang",shortcut:"5"},requirements:["systemId"],validate:({engine,input})=>{const region=engine.world.get(input.systemId);if(!region||region.type!=="cosmic.star-system"||region.parentSystemId)return "BIG_BANG requires a top-level region";if(engine.bigBang.status().active)return "BIG_BANG is already active";return true},execute:({engine,input})=>engine.bigBang.start({systemId:input.systemId,seed:input.seed??Date.now(),bounds:input.bounds})});
  engine.powers.register({id:"CREATE_SYSTEM",name:"Criar sistema estelar",version:"1.0.0",presentation:{label:"Criar sistema",icon:"✦",description:"Posicione um novo sistema no universo.",surface:"inventory",interaction:"system",shortcut:"1"},requirements:["universeId"],validate:({engine,input})=>isEntity(engine,input.universeId,"cosmic.empty-space")||"CREATE_SYSTEM requires a valid universeId",execute:({engine,input})=>{const system=engine.create("cosmic.star-system",input);engine.bus.emit("system:created",system);return system}});
  engine.powers.register({id:"CREATE_STAR",name:"Adicionar estrela",version:"1.0.0",presentation:{label:"Adicionar estrela",icon:"☀",description:"Escolha um tipo de estrela e posicione-o.",surface:"inventory",interaction:"star",shortcut:"2"},requirements:["systemId","templateId"],validate:({engine,input})=>isEntity(engine,input.systemId,"cosmic.star-system")&&template(engine,input.templateId,"star")||"CREATE_STAR requires a valid systemId and star template",execute:({engine,input})=>{const star=entityFromTemplate(engine,"cosmic.star",input.templateId,input,{systemId:input.systemId});engine.bus.emit("star:created",star);return star}});
  registerSDKPower(engine,{id:"CREATE_BLACK_HOLE",name:"Criar buraco negro",version:"2.0.0",presentation:{label:"Adicionar buraco negro",icon:"◌",description:"Posicione um buraco negro no sistema atual.",surface:"inventory",interaction:"blackhole",shortcut:"4"},sdk:true,requirements:["systemId","positionAU"],validate:({context,input})=>context.query.entity(input.systemId)?.type==="cosmic.star-system"&&Number.isFinite(input.massSolar??10)&&(input.massSolar??10)>0&&Number.isFinite(input.positionAU?.x)&&Number.isFinite(input.positionAU?.y)||"CREATE_BLACK_HOLE requires a system, positive mass, and AU coordinates",execute:({context,input})=>{const blackHole=context.commands.dispatch({type:"CreateEntity",entityType:"cosmic.black-hole",properties:{...input,massSolar:input.massSolar??10}});context.events.emit("black-hole:created",blackHole);return blackHole}});
  engine.powers.register({id:"CREATE_PLANET",name:"Criar planeta",version:"1.1.0",presentation:{label:"Adicionar planeta",icon:"◉",description:"Escolha um planeta e defina sua órbita.",surface:"inventory",interaction:"planet",shortcut:"3"},requirements:["systemId","parentStarId","templateId","semiMajorAxisAU","periodDays"],validate:({engine,input})=>{if(!isEntity(engine,input.systemId,"cosmic.star-system"))return "CREATE_PLANET requires a valid systemId";const star=engine.world.get(input.parentStarId);if(!star||star.type!=="cosmic.star"||star.systemId!==input.systemId)return "CREATE_PLANET requires a star in the selected system";if(!template(engine,input.templateId,"planet"))return "CREATE_PLANET requires a planet template";if(!(input.semiMajorAxisAU>0)||!(input.periodDays>0)||input.eccentricity<0||input.eccentricity>=1)return "CREATE_PLANET requires valid orbital parameters";if(findOrbitConflict(engine,input))return "CREATE_PLANET requires an unoccupied orbit";return true},execute:({engine,input})=>{const orbit=engine.create("cosmic.orbit",input);const star=engine.world.get(input.parentStarId);const environment=classifyOrbit(star,orbit.semiMajorAxisAU);const planet=entityFromTemplate(engine,"cosmic.terrestrial-planet",input.templateId,input,{systemId:input.systemId,parentStarId:input.parentStarId,orbitId:orbit.id,environment,orbit:{semiMajorAxisAU:orbit.semiMajorAxisAU,eccentricity:orbit.eccentricity,phaseRadians:orbit.phaseRadians,periodDays:orbit.periodDays,parentStarId:orbit.parentStarId}});engine.bus.emit("planet:created",planet);engine.bus.emit("planet:placed",Object.freeze({planetId:planet.id,orbitId:orbit.id,systemId:input.systemId,parentStarId:input.parentStarId}));return Object.freeze({planet,orbit})}});
  registerSDKPower(engine,{id:"DESTROY_PLANET",name:"Destruir planeta",version:"2.0.0",presentation:{label:"Destruir planeta",icon:"✕",description:"Remover o planeta selecionado e sua órbita.",surface:"selection",interaction:"destroy-selected"},sdk:true,requirements:["planetId"],validate:({context,input})=>context.query.entity(input.planetId)?.type==="cosmic.terrestrial-planet"||"DESTROY_PLANET requires a valid planetId",execute:({context,input})=>{const planet=context.query.entity(input.planetId),orbitId=planet.orbitId;const removedPlanet=context.commands.dispatch({type:"RemoveEntity",entityId:planet.id});const removedOrbit=orbitId?context.commands.dispatch({type:"RemoveEntity",entityId:orbitId}):null;const result=Object.freeze({planet:removedPlanet,orbit:removedOrbit});context.events.emit("planet:destroyed",result);return result}});
 }
};
