import{EventBus}from"./event-bus.js";import{Registry}from"./registry.js";import{UniverseState,createLegacyUniverseAdapter}from"./universe-state.js";import{TemplateRegistry}from"./template-registry.js";import{PowerRegistry}from"./power-registry.js";import{createEntityId,createEntityRecord,createPlanetEntity,createStarEntity}from"./entity-model.js";import{CommandBus,DomainError}from"./command-bus.js";
export class GenesisEngine{
 constructor(){this.bus=new EventBus();this.registry=new Registry();this.state=new UniverseState();this.world=this.state.world;this.templates=new TemplateRegistry();this.powers=new PowerRegistry();this.modules=new Map();this.commands=new CommandBus(this);this.legacyUniverse=createLegacyUniverseAdapter(this.state,command=>this.commands.dispatch(command));this.world=this.legacyUniverse.world}
 use(module){if(this.modules.has(module.id))throw new Error("Module already installed: "+module.id);module.install?.(this);this.modules.set(module.id,Object.freeze({id:module.id,version:module.version||"1.0.0"}));this.bus.emit("module:installed",{id:module.id});return this}
 create(type,props={}){return this.commands.dispatch({type:"CreateEntity",entityType:type,properties:props})}
 createEntity(type,props={}){const def=this.registry.get(type);if(!def)throw new DomainError("UNKNOWN_ENTITY_TYPE","Unknown creation type: "+type,{entityType:type});const identity={id:createEntityId(),schemaVersion:def.schemaVersion||1,createdAt:Date.now(),properties:def.create(props)};const factory=type==="cosmic.star"?createStarEntity:type==="cosmic.terrestrial-planet"?createPlanetEntity:null;const entity=factory?factory(identity):createEntityRecord({type,...identity});const saved=this.world.add(entity);this.bus.emit("entity:created",saved);return saved}
 remove(id){return this.commands.dispatch({type:"RemoveEntity",entityId:id})}
 removeEntity(id){if(typeof id!=="string"||!id)throw new DomainError("INVALID_ENTITY_ID","A non-empty entity id is required",{entityId:id});const removed=this.world.remove(id);if(removed)this.bus.emit("entity:destroyed",removed);return removed}
 setEntityProperty(id,property,value){return this.commands.dispatch({type:"SetEntityProperty",entityId:id,property,value})}
 updateEntity(id,changes){return this.commands.dispatch({type:"UpdateEntity",entityId:id,changes})}
 updateEntityProperties(id,changes){const supported=new Set(["name","massSolar","massEarth","radiusSolar","radiusEarth","radiusAU","temperatureK","densityKgM3","luminositySolar","position","positionAU","velocityAUPerSecond","semiMajorAxisAU","eccentricity","periodDays","phaseRadians","environment","metadata","life","lifeStage","atmosphere","earthLike","parentStarId","orbit","eventHorizonRadiusAU","captureRadiusAU","collisionCount","lastCollisionAt","regionId"]);if(!changes||typeof changes!=="object"||Array.isArray(changes)||!Object.keys(changes).length)throw new DomainError("INVALID_ENTITY_UPDATE","An entity update requires at least one property");const entity=this.world.get(id);if(!entity)throw new DomainError("ENTITY_NOT_FOUND",`Entity not found: ${id}`,{entityId:id});for(const[property,value]of Object.entries(changes)){if(!supported.has(property))throw new DomainError("UNSUPPORTED_ENTITY_PROPERTY",`Unsupported entity property: ${property}`,{property});const numeric=new Set(["massSolar","massEarth","radiusSolar","radiusEarth","radiusAU","temperatureK","densityKgM3","luminositySolar","semiMajorAxisAU","eccentricity","periodDays","phaseRadians","eventHorizonRadiusAU","captureRadiusAU","collisionCount","lastCollisionAt"]);if(numeric.has(property)&&!Number.isFinite(value))throw new DomainError("INVALID_PROPERTY_VALUE",`${property} must be finite`,{property});if(property==="name"&&(typeof value!=="string"||!value.trim()))throw new DomainError("INVALID_PROPERTY_VALUE","name must be a non-empty string",{property});if(["position","positionAU","velocityAUPerSecond"].includes(property)&&(!value||!Number.isFinite(value.x)||!Number.isFinite(value.y)))throw new DomainError("INVALID_PROPERTY_VALUE",`${property} must contain finite x and y coordinates`,{property});if(property==="orbit"&&(!value||typeof value!=="object"||Array.isArray(value)))throw new DomainError("INVALID_PROPERTY_VALUE","orbit must be an object",{property});if(["metadata","environment"].includes(property)&&(!value||typeof value!=="object"||Array.isArray(value)))throw new DomainError("INVALID_PROPERTY_VALUE",`${property} must be an object`,{property})}const updated=this.world.update(id,changes);this.bus.emit("entity:updated",Object.freeze({entity:updated,properties:Object.freeze(Object.keys(changes))}));return updated}
 usePower(id,input={}){return this.commands.dispatch({type:"ExecutePower",powerId:id,input})}
 executePower(id,input={}){return this.powers.execute(id,this,input)}
}
